In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
from pyxlsb import open_workbook as open_xlsb

%matplotlib inline

In [55]:
import pandas as pd
from pyxlsb import open_workbook as open_xlsb

df = []

with open_xlsb('Shogun Report Nov 2018.xlsb') as wb:
    with wb.get_sheet(1) as sheet:
        for row in sheet.rows():
            df.append([item.v for item in row])

df = pd.DataFrame(df[1:], columns=df[0])

In [56]:
df=df.drop(['SEQUENCE','Sr. No.','NET_SALES_QTY','NET_SALES_Cases.Units','UPC','NET_SALES_VALUE','SCHEME_DISCOUNT','OTHER_DISCOUNT','TAX_PERCENTAGE','Net Value Calculation','MRP','TUR','PARTY_CODE','BASEPACK CODE','SKU7_CODE','PRODUCT_NAME',],axis=1)
df.head()

,Delivery Date,VEHICLE,BEAT_NAME,PARTY_HLL_CODE,SERVICING PLG,PARTY_NAME,BILL_NUMBER,BILL_DATE,NET_SALES_WEIGHT_IN_KGS,BILL VALUE
0,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,1.080,9916.0
1,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,0.000,0.0
2,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,0.200,0.0
3,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,4.800,0.0
4,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,3.000,0.0

In [59]:
import pandas as pd
from pyxlsb import open_workbook as open_xlsb

df1 = []

with open_xlsb('GPS Location Data.xlsb') as wb:
    with wb.get_sheet(1) as sheet:
        for row in sheet.rows():
            df1.append([item.v for item in row])

df1 = pd.DataFrame(df1[1:], columns=df1[0])

In [60]:
df1

,PARTY_HLL_CODE,Current Latitude,Current Longitude,Verified,Current Latitude,Current Longitude
0,HUL-410243D-CH0103,12.948525,80.151653,True,12.951466,80.146496
1,HUL-410243D-CH0109,12.950331,80.151300,True,12.950532,80.150299
2,HUL-410243D-P18928,12.951595,80.143698,True,12.950693,80.145739
3,HUL-410243D-CH0114,12.948965,80.151099,True,12.949779,80.148689
4,TN60004462137,12.951610,80.141493,True,12.946263,80.146728
...,...,...,...,...,...,...
683,HUL-410243D-P17656,12.976948,80.183063,True,12.976948,80.183063
684,HUL-410243D-P35330,12.976275,80.144908,True,12.976275,80.144908
685,HUL-410243D-P49495,12.972210,80.157033,True,12.972210,80.157033
686,HUL-410243D-P49791,12.975892,80.146835,True,12.975892,80.146835
687,HUL-41A237D-P3880554,12.960030,80.140606,True,12.960030,80.140606

In [61]:
fin=pd.merge(df, df1, on=['PARTY_HLL_CODE'])

In [62]:
fin

,Delivery Date,VEHICLE,BEAT_NAME,PARTY_HLL_CODE,SERVICING PLG,PARTY_NAME,BILL_NUMBER,BILL_DATE,NET_SALES_WEIGHT_IN_KGS,BILL VALUE,Current Latitude,Current Longitude,Verified,Current Latitude,Current Longitude
0,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,1.080,9916.0,12.948525,80.151653,True,12.951466,80.146496
1,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,0.000,0.0,12.948525,80.151653,True,12.951466,80.146496
2,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,0.200,0.0,12.948525,80.151653,True,12.951466,80.146496
3,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,4.800,0.0,12.948525,80.151653,True,12.951466,80.146496
4,43405.0,VAN3 (RAJKUMAR),D-CHROMPET 1,HUL-410243D-CH0103,DETS-S,Jayapal Store (Ch)-D-D-D,GST43677,43434.0,3.000,0.0,12.948525,80.151653,True,12.951466,80.146496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44761,43434.0,BIKE (B SUNDARAPANDI),P - MR - NANGANALLUR1,HUL-410243D-P14526,PP-S,Sri sai pharmacy(mad)(KK)-D-D-P,GST43609,43433.0,0.030,0.0,12.971769,80.190906,True,12.974610,80.192244
44762,43434.0,BIKE (B SUNDARAPANDI),P - MR - NANGANALLUR1,HUL-410243D-P14526,PP-S,Sri sai pharmacy(mad)(KK)-D-D-P,GST43609,43433.0,0.030,0.0,12.971769,80.190906,True,12.974610,80.192244
44763,43434.0,BIKE (B SUNDARAPANDI),P - MR - NANGANALLUR1,HUL-410243D-P14526,PP-S,Sri sai pharmacy(mad)(KK)-D-D-P,GST43609,43433.0,0.084,0.0,12.971769,80.190906,True,12.974610,80.192244
44764,43434.0,BIKE (B SUNDARAPANDI),P - MR - NANGANALLUR1,HUL-410243D-P14526,PP-S,Sri sai pharmacy(mad)(KK)-D-D-P,GST43609,43433.0,0.060,0.0,12.971769,80.190906,True,12.974610,80.192244
44765,43434.0,BIKE (B SUNDARAPANDI),P - MR - NANGANALLUR1,HUL-410243D-P14526,PP-S,Sri sai pharmacy(mad)(KK)-D-D-P,GST43609,43433.0,0.084,0.0,12.971769,80.190906,True,12.974610,80.192244